version: '3.7'

services:

  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    command: bash -c "apt update && apt install -y default-jre && python3 -m cat.main"
    depends_on:
      - cheshire-cat-vector-memory
    ports:
      - ${CORE_PORT:-1865}:80
      - 5678:5678
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
      - CORE_HOST=${CORE_HOST:-localhost}
      - CORE_PORT=${CORE_PORT:-1865}
      - QDRANT_HOST=${QDRANT_HOST:-cheshire_cat_vector_memory}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - CORE_USE_SECURE_PROTOCOLS=${CORE_USE_SECURE_PROTOCOLS:-}
      - API_KEY=${API_KEY:-}
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
      - DEBUG=${DEBUG:-true}
      - SAVE_MEMORY_SNAPSHOTS=${SAVE_MEMORY_SNAPSHOTS:-false}
      # - JAVA_HOME=/usr/lib/jvm/java-11-openjdk
    volumes:
      - ./static:/app/cat/static
      - ./plugins:/app/cat/plugins
      - ./data:/app/cat/data
      - ./fastembed_cache:/tmp/fastembed_cache
      - ./wordlist:/app/cat/wordlist
      # - site-packages:/usr/local/lib/python3.10/site-packages
      # - ./.java:/usr/lib/jvm
    restart: unless-stopped

  # java:
  #   image: alpine:latest
  #   container_name: java_cat
  #   working_dir: /java
  #   command: "apk add openjdk11"
  #   volumes:
  #     - ./.java/:/usr/lib/jvm

  cheshire-cat-vector-memory:
    image: qdrant/qdrant:v1.9.1
    container_name: cheshire_cat_vector_memory
    expose:
      - 6333
    volumes:
      - ./cat/long_term_memory/vector:/qdrant/storage
    restart: unless-stopped

# volumes:
#   - site-packages: {}